### ISSUE TITLE
Add Horizonpedia App to Website

### ISSUE THREAD

**Issue by KevinCCucumber** [Nookipedia/acnh.directory#15]
Website: horizonpedia.com
Android: https://play.google.com/store/apps/details?id=com.wegner.horizonpedia
iOS: https://testflight.apple.com/join/cYhwMhdD
Discord: https://discord.gg/pQMRkMg
Twitter: https://twitter.com/HorizonpediaE
Instagram: https://www.instagram.com/horizonpedia/

Platforms:
- Android
- iOS (Testflight)

Informations are:
- all

Tools are:
- Checklist
- Fake Art Detection
- Wiki

Logos:
![app_logo_nobg](https://user-images.githubusercontent.com/49205361/95477532-bc0b6e00-0988-11eb-9c05-377df6ebbece.png)
![app_banner](https://user-images.githubusercontent.com/49205361/95477579-cb8ab700-0988-11eb-8f5e-b88353ea2cd1.png)

**Comment by KevinPayravi** [comment]
Resolved with https://github.com/Nookipedia/acnh.directory/pull/19
